### ISSUE TITLE
Add dot plot comparing categorical and continuous features

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [ucscXena/ucsc-xena-client#556]
From original [requirements doc](https://docs.google.com/document/d/130sokyqFEllUI4dXV8jo9E8SN86p7_IgC5YBjkfTGIw/edit):

Xena chart is implemented using the Highchart library. Highchart has a bubble chart mode (https://www.highcharts.com/demo/bubble).

**Dot plot comparing categorical (1) ~ continuous features (>1)**
e.g. a panel of gene expression across a set of different cell types, particularly when there are a lot of  genes or categories)

![Screen Shot 2022-04-28 at 3.47.30 PM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/57b0305a-b28e-46c7-8921-1c55e3e3839c)

The above is an example of categorical value (y) ~ continuous value (x) dot plot.  Here the dot radius and the shade of the dot both represent the average value of the continuous feature in the corresponding category. The color scale needs to be decided.

This is essentially the same data as the bookmark below, but a different view that only shows mean/average, not distribution https://xenabrowser.net/heatmap/?bookmark=2e9f881e6a18197ddc548f12df3f9b5e 

**Options**
x and y can be swapped in display. 

**Advanced options**
Continue feature value transformation, these are essentially the same as the options in [bookmark above](https://xenabrowser.net/heatmap/?bookmark=2e9f881e6a18197ddc548f12df3f9b5e), but the wording needs to be modified from "y unit" to "continuous data unit", "y data" to "continuous data". This is because the continuous data can be on the x or y axis, depending if they swap the axes.

**Comment by frano-m** [comment]
- [ ] Add [single cell data](https://github.com/ucscXena/ucsc-xena-client/issues/689) mode,
- [ ] Add [stats](https://github.com/ucscXena/ucsc-xena-client/issues/690),
- [ ] Add legend,
- [ ] Add legend title `'Mean value'`, `'Mean normalized value'` and `'Mean z-score'`,
- [ ] Add the sample size for a dot to the tooltip under mean e.g. `N=sample size`,
- [ ] Update scatter plot default color to `#3366CC`,
- [ ] Switch x and y axis titles on dot chart,
- [ ] Make dot chart the default if the number of resulting graphs will be more than 70,
- [ ] Update Advanced Options dropdown label,
- [ ] Bug fix single cell data.
